# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-14 17:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, default='Yeah! I am at HUSKY!', max_length=100, null=True)),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_pics')),
                ('secondary_email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('fb', models.CharField(blank=True, default='http://facebook.com/', max_length=1000, null=True)),
                ('instagram', models.CharField(blank=True, default='http://instagram.com/', max_length=1000, null=True)),
                ('github', models.CharField(blank=True, default='http://github.com/', max_length=1000, null=True)),
                ('linkedin', models.CharField(blank=True, default='http://linkedin.com/', max_length=200, null=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers_profile', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following_profile', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile_data',
            },
        ),
    ]
